### ISSUE TITLE
Test Cases for Sign Up Page

### ISSUE THREAD

**Issue by halfofning** [gabriel-lau/To-Do_Application#15]
Follow up from the documentation from Sprint 1, Issue #3.

Documentation of test cases for the Sign Up scenario.

**Comment by janinedesiree** [comment]
TC01 - test_SignUpWithValidCredentials

**Passing/Failing?:** Passing

**Test Description:** 
This is to test that users are able to create a new account using valid credentials

**Preconditions:** 
“jdesiree”  must not be already in use as a username

**Test Steps:**
1. Navigate to the sign up page
2. Enter “jdesiree” in “username” field
3. Enter "ephemeral12" in “password” field
4. Enter "ephemeral12" in “confirm password” field
5. Click on “Sign Up” button

**Expected Results:**
User is redirected to login page upon successfully registration and is prompted to log in

**Actual Results:**
As expected


——————


TC02 - test_CantSignUpWithExistingUsername

**Passing/Failing?:** Failing

**Test Description:** 
This is to test that users are unable to sign up using a username that is already in use

**Preconditions:** 
“jdesiree”  must already be in use (run this after TC01)

**Test Steps:**
1. Navigate to the sign up page
2. Enter “jdesiree” in “username” field
3. Enter "ephemeral12" in “password” field
4. Enter "ephemeral12" in “confirm password” field
5. Click on “Sign Up” button

**Expected Results:**
User is unable to sign up and error message showing "A user with that username already exists." is shown.

**Actual Results:**
As expected


——————


TC03 - test_InvalidSignupPasswordTooSimilarToInfo

**Passing/Failing?:** Failing

**Test Description:** 
This is to test that users are unable to sign up using a password that is too similar to their username

**Preconditions:** 
NIL

**Test Steps:**
1. Navigate to the sign up page
2. Enter “testuser1” in “username” field
3. Enter "testuser1" in “password” field
4. Enter "testuser1" in “confirm password” field
5. Click on “Sign Up” button

**Expected Results:**
User is unable to sign up and error message showing "The password is too similar to the username." is shown.

**Actual Results:**
As expected


——————


TC04 - test_InvalidSignupPasswordEntirelyNumeric

**Passing/Failing?:** Failing

**Test Description:** 
This is to test that users are unable to sign up using a password that comprises of all numbers

**Preconditions:** 


**Test Steps:**
1. Navigate to the sign up page
2. Enter “testuser1” in “username” field
3. Enter “12345678” in “password” field
4. Enter “12345678” in “confirm password” field
5. Click on “Sign Up” button

**Expected Results:**
User is unable to sign up and error message showing "This password is entirely numeric." is shown.

**Actual Results:**
As expected


——————


TC05 - test_InvalidSignupPasswordTooCommon

**Passing/Failing?:** Failing

**Test Description:** 
This is to test that users are unable to sign up using a password that is too common

**Preconditions:** 
NIL

**Test Steps:**
1. Navigate to the sign up page
2. Enter “testuser1” in “username” field
3. Enter “password” in “password” field
4. Enter “password” in “confirm password” field
5. Click on “Sign Up” button

**Expected Results:**
User is unable to sign up and error message showing "This password is too common." is shown.

**Actual Results:**
As expected


——————


TC06 - test_InvalidSignupPasswordLessThanEightChars

**Passing/Failing?:** Failing

**Test Description:** 
This is to test that users are unable to sign up using a password that is less than 8 characters long

**Preconditions:**
NIL

**Test Steps:**
1. Navigate to the sign up page
2. Enter “testuser1” in “username” field
3. Enter “pass” in “password” field
4. Enter “pass” in “confirm password” field
5. Click on “Sign Up” button

**Expected Results:**
User is unable to sign up and error message showing "This password is too short. It must contain at least 8 characters." is shown.

**Actual Results:**
As expected

**Comment by janinedesiree** [comment]
**6/6 Test Cases passed**
**Passing:** 1
**Failing:** 5
