### ISSUE TITLE
Test Cases for To-Do Page (2)

### ISSUE THREAD

**Issue by halfofning** [gabriel-lau/To-Do_Application#16]
Follow up from the documentation from Sprint 1, Issue #4.

Documentation of test cases for the To-Do Page scenario including:
- To-Do items filtered to Users. i.e. Only To-Do items created by Owner is shown.
- Addition and deletion of To-Do items auto archived instead of the current manual process.
- All To-Do items to have a timestamp added upon creation automatically by the application.

**Comment by janinedesiree** [comment]
TC01 - test_DisplayUniqueListofItems

**Passing/Failing?:** Failing

**Test Description:**
This is to test that users are unable to see the to-do list of other users

**Preconditions**
“myusername” is an existing account

**Test Values**
First sign up:
“myusername” in “username” field
“mypassword” in “password” field

At To-Do page:
“only for myusername” in “content” field

Second sign up:
“admin” in “username” field
“adminpassword” in “password” field

**Test Steps:**
1. Navigate to the login page which redirects users not signed in to the login page
2. Enter “myusername” in “username” field
3. Enter “mypassword” in “password” field
4. Click on “Login” button
5. Enter “only for myusername” in “content” field
6. Click on “Add” button
7. Logout and navigate to login page which redirects users not signed in to the login page
8. Enter “admin” in “username” field
9. Enter “adminpassword” in “password” field
10. Click on “Login”

**Expected Results**
User is redirected to the To-do list of user “Admin”, whereby the latest item in “myusername”’s list, “only for my username” is not displayed

**Actual Results:**
As expected


—————


TC02 - test_TimestampInTodo

**Passing/Failing?:** Passing

**Test Description:**
This is to test that new items added by users to the To-Do list have a timestamp

**Preconditions**
User is already logged in and is at To Do page

**Test Values**
“Hey!” in content field

Test Steps:
1. Enter “Hey!” in “content” field
2. Click on “Add” button

**Expected Results**
Timestamp showing time (in either a.m. or p.m.) of upload is displayed

**Actual Results:**
As expected

**Comment by janinedesiree** [comment]
**2/2 Test Cases passed**
**Passing:** 1
**Failing:** 1
