### ISSUE TITLE
Test Cases for To-Do History Page (2)

### ISSUE THREAD

**Issue by halfofning** [gabriel-lau/To-Do_Application#17]
Follow up from the documentation from Sprint 1, Issue #5 .

Documentation of test cases for the To-Do History Page scenario including:
- History of all To Do items added and deleted. (+ deleted to-do items in this sprint)

**Comment by janinedesiree** [comment]
TC01 - test_DisplayAddedItemToHistList

**Passing/Failing?:** Passing

**Test Description:**
This is to test that items that users have added to To-Do List are added to To-Do History automatically

**Preconditions**
The user is logged in

**Test Values**
Login:
“myusername” in “username” field
“mypassword” in “password” field

To-Do Page:
“only for myusername” in “content” field


**Test Steps:**
1. Navigate to the login page which redirects users not signed in to the login page
2. Enter “myusername” in “username” field
3. Enter “mypassword” in “password” field
4. Click on “Login” button
5. Enter “only for myusername” in “content” field
6. Click on “Add” button
7. Navigate to To-Do History page


**Expected Results**
“only for myusername” is added to the list on To-Do History page

**Actual Results:**
As expected


—————



TC02 - test_DisplayDeletedInArchive

**Passing/Failing?:** Passing

**Test Description:**
This is to test that items that users have deleted from To-Do List remain in the To-Do History page

**Preconditions**
The user is logged in (can be together with previous test case)

**Test Values**
To-Do Page:
“This should be in archive!” in “content” field


**Test Steps:**
1. Navigate to to-do page
2. Enter “This should be in archive!” in “content” field
3. Click on “Delete” button
4. Navigate to To-Do History page


**Expected Results**
“This should be in archive!” is still in the list on To-Do History page

**Actual Results:**
As expected


—————




TC03 - test_DisplayUniqueArchivedListofItems

**Passing/Failing?:** Failing

**Test Description:**
This is to test that users are unable to see the To-Do history of other users

**Preconditions**
“Myusername” must have entered “only for myusername” in her own to-do list and hence is displayed in her own to-do history page

Log out of “myusername” and log in to “admin”, ensuring she has not entered the test value, “only for myusername”, in her own to-do list

**Test Values**
Login page:
“admin” in “username” field
“adminpassword” in “password” field

**Test Steps:**
1. Log out
2. Navigate to todo page and be redirected to login page
3. Enter “admin” in “username” field
4. Enter “adminpassword” in “password” field
5. Navigate to To Do History page


**Expected Results**
“only for myusername” is not shown in the list on To-Do History page

**Actual Results:**
As expected

**Comment by janinedesiree** [comment]
**3/3 Test Cases passed**
**Passing:** 2
**Failing:** 1

**Comment by gabriel-lau** [comment]
(Test)

[Project Kavala Gantt Chart.xlsx](https://github.com/gabriel-lau/To-Do_Application/files/4126006/Project.Kavala.Gantt.Chart.xlsx)
