### ISSUE TITLE
Test Cases for User Login Page

### ISSUE THREAD

**Issue by halfofning** [gabriel-lau/To-Do_Application#3]
Documentation of unit tests for the user login page.

**Comment by janinedesiree** [comment]
TC01 - test_LoginwithUsernameandPassword

**Passing/Failing?:** 
Passing

**Test Description:**
This is to test whether user can be logged in with the correct username and password

**Preconditions**
Valid login credentials have been created

**Test Values**
“myusername” in “username” field
“mypassword” in “password” field

**Test Steps:**
1. Navigate to the todo page which redirects users not signed in to the login page
2. Enter “myusername” in “username” field
3. Enter “mypassword” in “password” field
4. Click on “Login” button



**Expected Results**
Users are redirected to the To-Do Page

**Actual Results:**
As expected


—————


TC02 - test_Navigate-To-ToDoPage

**Passing/Failing?:** 
Passing

**Test Description:**
This is to test whether user can navigate to To Do page after page logging in

**Preconditions**
The user has been successfully logged in

**Test Values**
NIL

**Test Steps:**
1. Navigate to the todo page

**Expected Results**
Users are redirected to the To-Do Page

**Actual Results:**
As expected


—————


TC03 - test_Navigate-To-ToDoHistoryPage

**Passing/Failing?:** 
Passing

**Test Description:**
This is to test whether users are able to navigate to To Do History page after logging in

**Preconditions**
The user has been successfully logged in

**Test Values**
NIL

**Test Steps:**
1. Navigate to the To Do History page

**Expected Results**
Users are redirected to the To-Do History Page

**Actual Results:**
As expected


—————



TC04 - test_Logout

**Passing/Failing?:** 
Passing

**Test Description:**
This is to test that users can logout

**Preconditions**
User is currently logged in

**Test Values**
NIL

**Test Steps:**
1. Navigate to logout page

**Expected Results**
User is logged out successfully with message confirming this

**Actual Results:**
As expected


—————


TC05-1 - test_InvalidLogin

**Passing/Failing?:** 
Failing

**Test Description:**
This is to test whether user can login with incorrect password

**Preconditions**
User is logged out, username used exists in database

**Test Values**
“myusername” in “username” field
“wrongpassword” in “username” field

**Test Steps:**
1. Navigate to login page
2. Enter “myusername” in “username” field
3. Enter “wrongpassword” in “username” field
4. Click on “Login” button

**Expected Results**
User cannot login, error message "Incorrect username and password. Please try again." displayed.

**Actual Results:**
As expected


—————


TC05-2 - test_InvalidLogin

**Passing/Failing?:** 
Failing

**Test Description:**
This is to test whether user can login with incorrect password

**Preconditions**
User is logged out

**Test Values**
“wrongusername” in “username” field
“wrongpassword” in “username” field

**Test Steps:**
1. Navigate to login page
2. Enter “wrongusername” in “username” field
3. Enter “wrongpassword” in “username” field
4. Click on “Login” button

**Expected Results**
User cannot login, error message "Incorrect username and password. Please try again." displayed.

**Actual Results:**
As expected


—————



TC06 - test_CannotNavigateToDoPage

**Passing/Failing?:** 
Failing

**Test Description:**
This is to test that users that are not logged in cannot navigate to the To-Do page

**Preconditions**
User is currently not logged in

**Test Values**
NIL

**Test Steps:**
1. Navigate to To-Do page

**Expected Results**
User is redirected to the login page and is prompted to login in to see the To-Do page

**Actual Results:**
As expected


—————


TC06 - test_CannotNavigateToDoHistory

**Passing/Failing?:** 
Failing

**Test Description:**
This is to test that users that are not logged in cannot navigate to the To-Do History page

**Preconditions**
User is currently not logged in

**Test Values**
NIL

**Test Steps:**
1. Navigate to To-Do History page

**Expected Results**
User is redirected to the login page and is prompted to login in to see the To-Do History page

**Actual Results:**
As expected

**Comment by janinedesiree** [comment]
**7/7 Test Cases passed**
**Passing:** 3
**Failing:** 4
