### ISSUE TITLE
Test Cases for To-Do Page

### ISSUE THREAD

**Issue by halfofning** [gabriel-lau/To-Do_Application#4]
Documentation of unit tests for the to-do page.

**Comment by janinedesiree** [comment]
TC01 - test_DisplayListOfItems

**Passing/Failing?:** 
Passing

**Test Description:**
This is to test whether To Do items from any users are shown in a list in the To Do page

**Preconditions**
User is logged in and has already added some items to her To-Do page

**Test Values**
NIL

**Test Steps:**
1. Navigate to the To-Do page

**Expected Results**
Users are brought to the To-Do page and items are displayed in a list

**Actual Results:**
As expected


—————


TC02 - test_AddBlankItem

**Passing/Failing?:** 
Failing

**Test Description:**
This is to test that users are not able to add a To Do Item with no input

**Preconditions**
User is logged in and is already on the To-Do page

**Test Values**
NIL

**Test Steps:**
1. Click on the “Add” button without entering any input in “content” field

**Expected Results**
Item is not added and error message pops up saying "Text field must be filled"

**Actual Results:**
As expected


—————


TC03 - test_AddValidItem

**Passing/Failing?:** 
Passing

**Test Description:**
This is to test that users can add a To Do Item with valid parameters

**Preconditions**
User is logged in and is already on the To-Do page

**Test Values**
"jd's test item" in “content” field

**Test Steps:**
1. Enter "jd's test item" in “content” field
2. Click on “Add” button

**Expected Results**
Item is added and displayed as last item on the list

**Actual Results:**
As expected


—————


TC04 - test_AddExistingItem

**Passing/Failing?:** 
Passing

**Test Description:**
This is to test that users can add a To Do item that already exists

**Preconditions**
User is logged in and is already on the To-Do page, “jd’s test item” has already been added (From previous test case”

**Test Values**
"jd's test item" in “content” field

**Test Steps:**
1. Enter "jd's test item" in “content” field
2. Click on “Add” button

**Expected Results**
Item is added and displayed as last item on the list

**Actual Results:**
As expected


—————


TC05 - test_DeleteItem

**Passing/Failing?:** 
Passing

**Test Description:**
This is to test that users can delete items in To-Do list

**Preconditions**
User is logged in and is already on the To-Do page, there are two “jd’s test item” items already added (From previous test case)

**Test Values**
NIL

**Test Steps:**
1. Click on “Delete” button beside latest “jd’s test item” on the list

**Expected Results**
Item is removed from the To-Do list

**Actual Results:**
As expected

**Comment by janinedesiree** [comment]
**5/5 Test Cases passed**
**Passing:** 4
**Failing:** 1
