### ISSUE TITLE
Test Cases for the To-Do History Page

### ISSUE THREAD

**Issue by halfofning** [gabriel-lau/To-Do_Application#5]
Documentation of unit tests for the to-do history page.

**Comment by janinedesiree** [comment]
TC01 - test_DisplayListofArchivedItems

**Passing/Failing?:** 
Passing

**Test Description:**
This is to test whether users can see a list of archived To Do items in To-Do History page

**Preconditions**
User is logged in and has archived some items to his To-Do History page

**Test Values**
NIL

**Test Steps:**
1. Navigate to the To-Do History page

**Expected Results**
Users are brought to the To-Do History page and items are displayed in a list

**Actual Results:**
As expected


—————


TC02 - test_ArchiveItem

**Passing/Failing?:** 
Passing

**Test Description:**
This is to test whether users are able to archive items, sending it to the To-Do History page

**Preconditions**
User is logged in and has some items in her To-Do list already

**Test Values**
NIL

**Test Steps:**
1. Navigate to the To-Do page
2. Click the “archive” button beside the last item on the list
3. Navigate to the To-Do History page

**Expected Results**
Users are brought to the To-Do History page and the item that was archived is displayed at the very bottom of the list

**Actual Results:**
As expected


—————


TC03 - test_ItemDeletedNotArchived

**Passing/Failing?:** 
Passing

**Test Description:**
This is to test whether items that users have deleted is not shown in To-Do History page

**Preconditions**
User is logged in and has deleted the item, “jd’s test item” from To-Do List (from previous test case whereby two of the exact items were added)

**Test Values**
NIL

**Test Steps:**
1. Navigate to the To-Do page

**Expected Results**
Users are brought to the To-Do History page and only one “jd’s test item” is displayed

**Actual Results:**
As expected

**Comment by janinedesiree** [comment]
**3/3 Test Cases passed**
**Passing:** 3
**Failing:** 0
