### ISSUE TITLE
Test Cases for the Team Contributions Page

### ISSUE THREAD

**Issue by halfofning** [gabriel-lau/To-Do_Application#6]
Documentation of unit tests for the team contributions page.

**Comment by janinedesiree** [comment]
Assignment does not require unit testing of any form

**Comment by janinedesiree** [comment]
TC01 - test_DisplayTeamContributions

**Passing/Failing?:** 
Passing

**Test Description:**
This is to test whether users can view the Team Contributions page

**Preconditions**
NIL

**Test Values**
NIL

**Test Steps:**
1. Navigate to the Team Contribution page

**Expected Results**
All 5 members’ roles and contributions are displayed clearly

**Actual Results:**
As expected


Note: This was purely manual testing
