### ISSUE TITLE
To-Do Page

### ISSUE THREAD

**Issue by halfofning** [gabriel-lau/To-Do_Application#8]
Addresses To-Do page test case scenarios referenced from #4.

**Comment by halfofning** [comment]
Commit b43b746 by @gabriel-lau on to-do page (view, delete, add) reviewed and pushed to master.

Incomplete:
Archive to to-do history button - assigned to @YUNT3NG.

**Comment by YUNT3NG** [comment]
Archive to to-do history button completed at commit 371f6c1. Please review @halfofning

**Comment by halfofning** [comment]
Looks good! Closing issue.
